### ISSUE TITLE
Please clarify why root access is required and if there is a way around?

### ISSUE THREAD

**Issue by yarikoptic** [trendscenter/coinstac-instructions#2]
Looking at https://github.com/trendscenter/coinstac-instructions/blob/master/coinstac-install-instructions-for-ubuntu-1604.md#run-application:

     gksudo ./coinstac

    A window will appear asking you to type in your user password. Please do so

I am not taking "Please give us root access" lightly, especially whenever there is no reason stated and AFAIK root access is not needed

**Comment by rssk** [comment]
Sorry for the late reply, these instructions appear to be out of date as well; Docker on linux needs root access to interact with the daemon, however users can add themselves to the `docker` group to get around needing permissions but there are still security implication in doing this and some inherent limitations of the Docker platform. We hope to address in the future for linux users by allowing singularity containers as an alternative

https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
